import Head from 'next/head'
import { useEffect } from 'react'
import useNewUser from '@/hooks/useNewUser'
import { useRouter } from 'next/router'
import Link from 'next/link'

export default function Home() {
  const router = useRouter()
  const [newUser] = useNewUser()

  useEffect(() => {
    if (newUser) {
      router.replace('/onboarding')
    }
  })

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <h2>메인 홈</h2>
      <Link href="sign-up">회원가입</Link>
    </>
  )
}
